# Generated by Django 3.2.6 on 2021-12-24 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaria',
            name='candidatos',
        ),
        migrations.AddField(
            model_name='diaria',
            name='candidatas',
            field=models.ManyToManyField(blank=True, related_name='candidatas', to=settings.AUTH_USER_MODEL),
        ),
    ]
