# Generated by Django 3.2.6 on 2021-09-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Servico',
        ),
    ]
